### ISSUE TITLE
Build error using new Go version.  x509_splice.go: "not enough arguments to buildExtensions"

### ISSUE THREAD

**Issue by jeffersoncarpenter** [namecoin/ncdns#58] opened 2017-11-27 07:39 UTC
Building with the latest stable version of Go, I get the following build error:

```
C:\Users\rofl\go>go get -t github.com/namecoin/ncdns/...
# github.com/namecoin/ncdns/x509
src\github.com\namecoin\ncdns\x509\x509_splice.go:67:36: not enough arguments in call to buildExtensions
        have (*Certificate)
        want (*Certificate, []byte)
```

The build succeeds with an older version.

**Comment by JeremyRand** [comment] 2017-11-27 20:49
Duplicate of https://github.com/namecoin/ncdns/issues/44 , please do a basic search before filing bugs.

**Closed by JeremyRand** 2017-11-27 20:49 UTC
Labels: duplicate
