### ISSUE TITLE
Build Failure: x509/x509_splice.go:67:36: not enough arguments in call to buildExtensions

### ISSUE THREAD

**Issue by ph1l** [namecoin/ncdns#55] opened 2017-11-16 20:51 UTC
running Debian sid.

```
$ mkdir .go
$ export GOPATH=${HOME}/.go
$ go get -d -t -u github.com/namecoin/ncdns/...
$ go generate github.com/namecoin/ncdns/...
$ go get -t github.com/namecoin/ncdns/...
# github.com/namecoin/ncdns/x509
.go/src/github.com/namecoin/ncdns/x509/x509_splice.go:67:36: not enough arguments in call to buildExtensions
        have (*Certificate)
        want (*Certificate, []byte)
```

**Comment by JeremyRand** [comment] 2017-11-18 18:35
Likely duplicate of https://github.com/namecoin/ncdns/issues/44

**Closed by JeremyRand** 2017-11-18 18:35 UTC
Labels: duplicate
